AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3BucketName:
    Type: String
    Default: valleyridge-inventory-sync
    Description: S3 bucket name for storing inventory files

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Environment:
      Variables:
        S3_BUCKET: !Ref S3BucketName
        SUPPORT_EMAIL: support@valleyridge.ca
        LOG_LEVEL: INFO

Resources:
  ProcessInventoryIncrementalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: valleyridge-process-inventory-incremental
      CodeUri: .
      Handler: incremental-processor.handler
      Runtime: nodejs20.x
      Description: Processes inventory files incrementally, generating delta files with only changed records
      Tags:
        Project: ValleyRidgeInventorySync
        Environment: Production
        Component: IncrementalProcessor
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - CloudWatchLogsFullAccess
        - CloudWatchFullAccess





Outputs:
  ProcessInventoryIncrementalFunction:
    Description: "Incremental Inventory Processing Lambda Function ARN"
    Value: !GetAtt ProcessInventoryIncrementalFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ProcessInventoryIncrementalFunction"

  S3BucketName:
    Description: "S3 Bucket name for inventory files"
    Value: !Ref S3BucketName
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketName" 